name: Test and publish

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Generate docs
        run: make run
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PERSONAL_TOKEN }}
          publish_dir: ./dist
