name: release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: make build
      - name: Test
        run: make test
  release:
    needs: build
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v4
      - name: Get ldflags
        id: ldflags
        run: echo "LDFLAGS=$(make ldflags)" >> "$GITHUB_OUTPUT"
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://dl.google.com/go/go1.23.1.linux-amd64.tar.gz"
          project_path: "./"
          ldflags: ${{ steps.ldflags.outputs.LDFLAGS }}
          binary_name: "auteur"
          extra_files: LICENSE README.md
