name: unit-tests

on:
  push:
    branches:
      - "**"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Install dependencies
        run: go get .
      - name: Build
        run: make build
      - name: Test
        run: make test
